Dz2
stopstress/RadyukAndroidPvt pull request #3
Opened 2019-06-19 21:04 UTC by stopstress

Dz2a & Dz2b

2019-06-21 09:21 UTC, stopstress commented
Заменил Picasso на Glide. 
Скриншоты финальной версии:
![Screenshot_1561108001](https://user-images.githubusercontent.com/46762401/59912550-ec8b6980-941e-11e9-9d7f-434b7fd4bb4b.png)
![Screenshot_1561108031](https://user-images.githubusercontent.com/46762401/59912551-ec8b6980-941e-11e9-8ffb-61555e5e1ae7.png)
![Screenshot_1561108057](https://user-images.githubusercontent.com/46762401/59912552-ed240000-941e-11e9-92aa-e0ca91a450e4.png)

2019-06-21 09:45 UTC, eugenia-shumeiko commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +            Glide.with(this)
В условиях дз еще был ProgressBar и listener, чтобы отслеживать процесс загрузки (или неудачи)

2019-06-22 07:25 UTC, stopstress commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +            Glide.with(this)
Ура, получилось) ProgressBar и Listener добавлены.

2019-06-22 12:33 UTC, tim-teacher requested changes

2019-06-22 12:33 UTC, jushlwest commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +                            Thread.sleep(3000)
не не нужно такой бред писать, вы же слипите UI поток, по сути на 3 секунды все приложение будет заморожено. Для этого есть другие варианты, рассмотрим потом на занятии.

2019-06-22 12:33 UTC, jushlwest commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +                        return false
тоесть если загрузка не удачная то прогрес бар будет продолжать крутиться и юзер будет думать что все еще идет загрузка?

2019-06-22 13:28 UTC, stopstress commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +                        return false
исправил на "return true" - но, если честно, так и не понял разницы

эксперимент с ошибочной ссылкой показал, что прогресс-бар продолжает крутиться и с true, и с false

было бы здОрово проговорить это на занятии в понедельник

2019-06-22 13:29 UTC, stopstress commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +                            Thread.sleep(3000)
ок, исправил: 

https://github.com/stopstress/RadyukAndroidPvt/blob/Dz2/app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt

2019-06-22 14:02 UTC, eugenia-shumeiko commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +                        return true
Здесь тоже нужно вручную прятать ProgressBar (причем лучше не INVISIBLE, а GONE) и выводить какое-нибудь сообщение, что произошла ошибка (например, Toast)

2019-06-22 14:39 UTC, stopstress commented on app/src/main/java/by/stress/radyukandroidpvt/dz2/Dz2bActivity.kt
> +                        return true
ценный комментарий, спасибо!
исправил)

2019-06-22 14:45 UTC, eugenia-shumeika approved these changes

2019-06-23 07:26 UTC, tim-teacher approved these changes

2019-06-23 07:42 UTC, merged